apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260626-200215-4zlld9qdfyd8-service
spec:
  selector:
    app: enterprise-system-20260626-200215-4zlld9qdfyd8
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
